import type { NextPage } from 'next';
import Head from 'next/head';
import Feature from '../components/Feature';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import Introduce from '../components/Introduce';
import ListProduct from '../components/ListProduct';
import Services from '../components/Services';
import Visualize from '../components/Visualize';
import { PRODUCT, SERVICES } from '../constants/common';
import { useProductListQuery } from '../services/blog';

const Home: NextPage = () => {
  const { data: blogs } = useProductListQuery();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Introduce />
      <Visualize />
      <ListProduct productItem={blogs} />
      <Services heading="What they say about our services" service={SERVICES} />
      <Footer />
    </>
  );
};

export default Home;
